### ISSUE TITLE
Check me out

### ISSUE THREAD

**Issue by bchr02** [bchr02/filejson#4]
Hello,

Since I noticed you have posted in other similar modules I thought I would CC you on this announcement.

filejson is a new module that allows you to store a value simply by doing `file.contents  = value` and have that and any future changes automatically saved to a JSON file on your drive. This will allow the variable to persist across app restarts. The important difference between this module and others is that you don't have to call a function every time you want to alter your objects value.  So, instead of having to wrap every update in a function/callback and creating a pyramid (aka callback hell):

``` javascript
var jsonfile = require('jsonfile');

var file = '/tmp/data.json';
var obj = {};

jsonfile.writeFile(file, obj, function (err) {
  if(err) {
    console.error(err);
    return;
  }
  obj.msg = "Hello World!";
  jsonfile.writeFile(file, obj, function (err) {
    if(err) {
      console.error(err);
      return;
    }
    obj.user = {"name": "Bob"};
    jsonfile.writeFile(file, obj, function (err) {
      if(err) {
        console.error(err);
        return;
      }
    });
  });
});
```

**With jsonfile you only need to wrap once and that's it:**

``` javascript
var Filejson = require("filejson");
var f = new Filejson();

f.load("file.json", function(error, file) {
  if(error) {
    console.error(error);
    return;
  }
  file.contents = {};
  file.contents.msg = "Hello World!";
  file.contents.user = {"name": "Bill"};
});
```

cc: @pinn3, @tankerkiller125, @hobberwickey, @YounessBenmouloud, @Lazarus118, @sahas, @ajsingh007, @dudleyjosh, @SCBuergel, @kamikazechaser, @Pizylon, @Egoscio, @maxime1992, @bajtos, @piranna, @sampathsris

**Comment by piranna** [comment]
The idea is not bad, but I have some questions/tasks for you:
- How do you manage (or prevent) people inserting random objects with functions or a class?
- What about references cycles?
- How is the performance to access big objects?
- Does it auto-reload when the file changed on the filesystem?
- Why you use a setTimeout() delay instead of write the changes on setInmediate()?

**Comment by tankerkiller125** [comment]
Thanks for the little notice. But next time just put it on npm and let people see it there. I do not enjoy getting random messages for projects I'm not already part of.

**Comment by bchr02** [comment]
> Thanks for the little notice. But next time just put it on npm and let people see it there. I do not enjoy getting random messages for projects I'm not already part of.

@tankerkiller125 My apologies for having disturbed you and anyone else who didn't wish to receive this notice.

**Comment by bchr02** [comment]
@piranna Thank you for your questions (and for not getting upset at me).

> How do you manage (or prevent) people inserting random objects with functions or a class?

Currently, filejson will use the default behavior of JSON.stringify whereby Non-enumerable properties will be ignored.

> What about references cycles?

Do you mean [this issue](http://stackoverflow.com/questions/11616630/json-stringify-avoid-typeerror-converting-circular-structure-to-json)? I could add a custom function to account for this. Currently, an error would be caught and pushed down through the callback.

> How is the performance to access big objects?

I have not yet run any benchmarks, but plan to soon.

> Does it auto-reload when the file changed on the filesystem?

Currently it does not, however if there is demand for this I may add this functionality. PR are also welcomed.

> Why you use a setTimeout() delay instead of write the changes on setImmediate()?

Your right perhaps setImmediate would be better. The thought was to limit excessive writes to the disk which will can inherently slow ones system down and create a race condition with fs.writeFile. Using setTimeout one could adjust the timeout based on their individual needs for maximum performance. Meanwhile, I avoid the race condition further by preventing simultaneous writes. However, this comes at the cost of possibly not having written the last set of changes to disk which I plan to address in a future update perhaps using setImmediate at which point I could consider switching over to setImmediate or at least make it optional.

**Comment by piranna** [comment]
> Currently, filejson will use the default behavior of JSON.stringify whereby Non-enumerable properties will be ignored.

You need to consider that if you aim for total transparency for the user, they will add them and there will be surprises. You should at least check and throw an exception, but should be better if you could do some intelligent string serialization and de-serialization for that.

> What about references cycles?
> 
> Do you mean this issue? I could add a custom function to account for this. Currently, an error would be caught and pushed down through the callback.

Yes, but also there's the problem for objects duplicities... How you'll do if an object is referenced from two places on the tree?

> How is the performance to access big objects?
> 
> I have not yet run any benchmarks, but plan to soon.

You should think on that, and also about some intelligent mapping to split the objects in several files and allow faster loading and access...

> Why you use a setTimeout() delay instead of write the changes on setImmediate()?
> 
> Your right perhaps setImmediate would be better. The thought was to limit excessive writes to the disk which will can inherently slow ones system down and create a race condition with fs.writeFile. Using setTimeout one could adjust the timeout based on their individual needs for maximum performance. Meanwhile, I avoid the race condition further by preventing simultaneous writes. However, this comes at the cost of possibly not having written the last set of changes to disk which I plan to address in a future update perhaps using setImmediate at which point I could consider switching over to setImmediate or at least make it optional.

Just queuing the write requests, writing on `setInmediate()` and setting a flag to prevent concurrent writes should be just enough. You can take a look on [async.js cargo()](http://caolan.github.io/async/docs.html#.cargo) function. You should also consider an objects diff mechanism to improve performance by not doing useless changes.

**Comment by bchr02** [comment]
> You need to consider that if you aim for total transparency for the user, they will add them and there will be surprises. You should at least check and throw an exception, but should be better if you could do some intelligent string serialization and de-serialization for that.

You are right. I agree with you and will update filejson so that it starts throwing an exception in that scenario. Also, I will consider intelligent string serialization and de-serialization. That's a good idea.

> Yes, but also there's the problem for objects duplicities... How you'll do if an object is referenced from two places on the tree?

To solve the problem of object duplicates and reference cycles, I can make use of [cycle.js](https://github.com/douglascrockford/JSON-js/blob/master/cycle.js). What do you think?

> You should think on that, and also about some intelligent mapping to split the objects in several files and allow faster loading and access...

Yes, I have thought about that and will definitely consider it.

> Just queuing the write requests, writing on setInmediate() and setting a flag to prevent concurrent writes should be just enough. You can take a look on async.js cargo() function. 

Okay, I will try this out.

> You should also consider an objects diff mechanism to improve performance by not doing useless changes.

Yes, I will consider this, good idea.

Something else I am considering is supporting the optional use of [sapienlab/jsonpack](https://github.com/sapienlab/jsonpack) (a compression algorithm for JSON). What do you think about that?

Thanks for all the feedback.

**Comment by bchr02** [comment]
Just pushed [1.0.6](https://github.com/bchr02/filejson/releases/tag/1.0.6) 

**Changes**
- new type checking - now throws when an incompatible value is used
- new speed configuration option to bypass new type checking
- using setImmediate instead of setTimeout for faster updating
- removed the timeout configuration option since we are no longer using setTimeout

Thank you @piranna for these suggestions.
